sudo: false

language: scala

jdk: oraclejdk8

scala:
  - 2.10.4
  - 2.10.6
  - 2.11.7
  - 2.11.11
  - 2.12.2
  - 2.12.4

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 test

notifications:
  email:
    recipients:
      - marcoonroad@gmail.com
    on_success: change
